#!/bin/bash

echo "🎉 MEAL GENERATOR WORKING! ✅"
echo "========================================"
echo ""
echo "Now let's test ALL other features systematically."
echo "This will take about 10-15 minutes total."
echo ""
echo "📱 Keep https://glp1-nutrition-sidekick.vercel.app open on your phone"
echo ""
echo "========================================"
echo ""

echo "PHASE 1: CORE AUTHENTICATION & PROFILE"
echo "----------------------------------------"
echo ""
echo "✅ TEST 1.1: Sign Out & Sign In"
echo "   Actions:"
echo "   1. Click your profile/account menu"
echo "   2. Click 'Sign Out'"
echo "   3. Sign back in with same credentials"
echo ""
echo "   Expected: Successfully signs out and back in"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 1.2: Profile Data Persistence"
echo "   Actions:"
echo "   1. After signing in, check your dashboard"
echo "   2. Verify your name/email shows correctly"
echo "   3. Check if calculator results are still saved"
echo ""
echo "   Expected: Your data persists across sessions"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 2: CALCULATOR & NUTRITION GOALS"
echo "----------------------------------------"
echo ""
echo "✅ TEST 2.1: View Saved Calculator Results"
echo "   Actions:"
echo "   1. Navigate to Calculator page"
echo "   2. Check if your previous TDEE/protein goals show"
echo ""
echo "   Expected: Shows your saved results"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 2.2: Update Calculator"
echo "   Actions:"
echo "   1. Change one value (e.g., weight or activity level)"
echo "   2. Recalculate"
echo "   3. Verify new results appear"
echo "   4. Refresh page - are new results still there?"
echo ""
echo "   Expected: Updates and saves new calculations"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 3: MEAL FEATURES"
echo "----------------------------------------"
echo ""
echo "✅ TEST 3.1: Browse Recipe Library"
echo "   Actions:"
echo "   1. Navigate to 'Browse Recipes' or 'Meals'"
echo "   2. Check if recipes load"
echo "   3. Try clicking on a recipe"
echo "   4. View recipe details"
echo ""
echo "   Expected: Recipe library loads with meals"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 3.2: Save a Meal"
echo "   Actions:"
echo "   1. Generate a meal OR find one in recipe library"
echo "   2. Look for 'Save' or bookmark icon"
echo "   3. Click to save the meal"
echo "   4. Navigate to 'Saved Meals' or 'Cookbook'"
echo "   5. Verify meal appears in saved list"
echo ""
echo "   Expected: Meal saves and appears in cookbook"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 3.3: Delete Saved Meal"
echo "   Actions:"
echo "   1. Go to saved meals"
echo "   2. Delete one meal"
echo "   3. Verify it's removed from list"
echo ""
echo "   Expected: Meal deletes successfully"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 3.4: Shopping List"
echo "   Actions:"
echo "   1. Navigate to Shopping List"
echo "   2. Try to add items (if feature exists)"
echo "   3. Check if items persist"
echo ""
echo "   Expected: Shopping list works (or shows upgrade prompt if premium)"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 4: TRACKING FEATURES"
echo "----------------------------------------"
echo ""
echo "✅ TEST 4.1: Injection Tracker"
echo "   Actions:"
echo "   1. Navigate to Injection Tracker (or Dashboard)"
echo "   2. Log a new injection"
echo "   3. Select medication, dose, injection site"
echo "   4. Save injection"
echo "   5. Verify it appears in history"
echo ""
echo "   Expected: Injection logs successfully"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 4.2: Meal Logging"
echo "   Actions:"
echo "   1. Navigate to Meal Log"
echo "   2. Log a meal (breakfast/lunch/dinner)"
echo "   3. Add protein and vegetable servings"
echo "   4. Save"
echo "   5. Check if it appears in today's log"
echo ""
echo "   Expected: Meal logs successfully (or upgrade prompt if premium)"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 4.3: Symptom Tracking"
echo "   Actions:"
echo "   1. Navigate to Symptoms page"
echo "   2. Log a symptom (nausea, fatigue, etc.)"
echo "   3. Rate severity (1-10)"
echo "   4. Add notes if possible"
echo "   5. Save"
echo "   6. Verify it appears in symptom history"
echo ""
echo "   Expected: Symptom logs successfully (or upgrade prompt if premium)"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 5: NAVIGATION & UX"
echo "----------------------------------------"
echo ""
echo "✅ TEST 5.1: Navigation Bar"
echo "   Actions:"
echo "   1. Click through all main navigation items"
echo "   2. Home, Meals, Calculator, Track, Settings, etc."
echo "   3. Verify each page loads without errors"
echo ""
echo "   Expected: All pages load correctly"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 5.2: Mobile Responsiveness"
echo "   Actions:"
echo "   1. Rotate phone (portrait to landscape)"
echo "   2. Check if layout adjusts properly"
echo "   3. Try zooming in/out"
echo "   4. Check if buttons are tappable (not too small)"
echo ""
echo "   Expected: App is mobile-friendly"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 5.3: Back Button & Navigation"
echo "   Actions:"
echo "   1. Navigate deep into the app (e.g., meal details)"
echo "   2. Use phone's back button"
echo "   3. Verify it goes back correctly"
echo "   4. Try browser forward/back buttons"
echo ""
echo "   Expected: Navigation works smoothly"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 6: EDGE CASES & ERRORS"
echo "----------------------------------------"
echo ""
echo "✅ TEST 6.1: Offline Behavior"
echo "   Actions:"
echo "   1. Turn on Airplane mode"
echo "   2. Try to use the app"
echo "   3. Turn off Airplane mode"
echo "   4. Verify app recovers"
echo ""
echo "   Expected: Shows offline message, recovers when back online"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 6.2: Invalid Form Data"
echo "   Actions:"
echo "   1. Try to submit calculator with empty fields"
echo "   2. Try negative numbers"
echo "   3. Try extremely large numbers"
echo ""
echo "   Expected: Shows validation errors, prevents submission"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 6.3: Session Persistence"
echo "   Actions:"
echo "   1. Keep app open for 5 minutes"
echo "   2. Lock your phone"
echo "   3. Unlock and return to app"
echo "   4. Try to use a feature (e.g., generate meal)"
echo ""
echo "   Expected: Session persists, no re-login required"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 7: SETTINGS & PREFERENCES"
echo "----------------------------------------"
echo ""
echo "✅ TEST 7.1: Settings Page"
echo "   Actions:"
echo "   1. Navigate to Settings"
echo "   2. Check what options are available"
echo "   3. Try changing a preference"
echo "   4. Save and verify it persists"
echo ""
echo "   Expected: Settings load and save correctly"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "✅ TEST 7.2: Evening Toolkit (if exists)"
echo "   Actions:"
echo "   1. Look for Evening Toolkit feature"
echo "   2. Try the mindful eating exercises"
echo "   3. Complete a session"
echo ""
echo "   Expected: Toolkit works for habit breaking"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "PHASE 8: PERFORMANCE & SPEED"
echo "----------------------------------------"
echo ""
echo "✅ TEST 8.1: Load Times"
echo "   Actions:"
echo "   1. Navigate to different pages"
echo "   2. Note if any pages are slow (>3 seconds)"
echo "   3. Test meal generation speed"
echo ""
echo "   Expected: Pages load quickly (under 2-3 seconds)"
echo "   ☐ PASS  ☐ FAIL  Slow pages: _______________"
echo ""

echo "✅ TEST 8.2: Multiple Meal Generations"
echo "   Actions:"
echo "   1. Generate 3-4 meals in a row"
echo "   2. Check if each generation works"
echo "   3. Verify variety (not repeating same meals)"
echo ""
echo "   Expected: Multiple generations work without errors"
echo "   ☐ PASS  ☐ FAIL  Notes: _______________"
echo ""

echo "========================================"
echo "📊 TESTING SUMMARY"
echo "========================================"
echo ""
echo "Count your results:"
echo "  ✅ PASSED: _____"
echo "  ❌ FAILED: _____"
echo "  ⚠️  ISSUES: _____"
echo ""
echo "========================================"
echo "🚨 REPORT FAILURES TO CLAUDE"
echo "========================================"
echo ""
echo "For each FAILED test, report:"
echo ""
echo "Test Name: [e.g., TEST 3.2: Save a Meal]"
echo "Error: [exact error message or description]"
echo "Steps: [what you did]"
echo "Expected: [what should happen]"
echo "Actual: [what actually happened]"
echo ""
echo "Screenshot if possible!"
echo ""
echo "========================================"
echo ""
echo "After testing, tell Claude:"
echo "  '✅ All tests passed!'"
echo "  OR"
echo "  '❌ Found X issues: [list them]'"
echo ""
