#!/bin/bash

echo "🧪 GLP-1 Nutrition App - Production Testing Checklist"
echo "====================================================="
echo ""
echo "📱 Open your Vercel deployment URL on your phone:"
echo "   https://glp1-nutrition-sidekick.vercel.app"
echo ""
echo "Follow this testing checklist:"
echo ""

echo "✅ TEST 1: Homepage Loads"
echo "   □ Page loads without errors"
echo "   □ You see 'Your GLP-1 Nutrition Companion' title"
echo "   □ 'Get Started' and 'Learn More' buttons visible"
echo ""

echo "✅ TEST 2: Sign Up / Sign In"
echo "   □ Click 'Get Started' button"
echo "   □ Create new account with email/password"
echo "   □ Verify you can sign in"
echo "   □ No errors in the sign up process"
echo ""

echo "✅ TEST 3: Onboarding Flow"
echo "   □ Calculator page loads"
echo "   □ Enter your age, weight, height, activity level"
echo "   □ Submit and get TDEE/protein calculations"
echo "   □ Results are saved"
echo ""

echo "✅ TEST 4: AI Meal Generation (THE BIG TEST!)"
echo "   □ Navigate to Meal Generator"
echo "   □ Click 'Generate Meal'"
echo "   □ 🔴 CRITICAL: Check if you get '401 error' (if yes, env vars not set)"
echo "   □ 🟢 SUCCESS: Meal options appear (if yes, everything works!)"
echo "   □ Meal has recipe details, ingredients, nutrition info"
echo ""

echo "✅ TEST 5: Other Features"
echo "   □ Browse recipe library works"
echo "   □ Injection tracker works"
echo "   □ Settings page loads"
echo "   □ Can log out and back in"
echo ""

echo "=================================================="
echo "📊 RESULTS INTERPRETATION:"
echo ""
echo "✅ If all tests pass → App is working perfectly!"
echo ""
echo "❌ If you get 401 error on meal generation:"
echo "   → Environment variables not set on Vercel"
echo "   → Go to Vercel dashboard > Settings > Environment Variables"
echo "   → Make sure all Firebase, OpenAI, Grok keys are added"
echo "   → Redeploy the app"
echo ""
echo "❌ If you get 403 error on meal generation:"
echo "   → Premium access check (but should be bypassed in dev mode)"
echo "   → Check if you're logged in"
echo ""
echo "❌ If Firebase auth errors:"
echo "   → Check NEXT_PUBLIC_FIREBASE_* variables are set"
echo ""
echo "=================================================="
echo ""
echo "After testing, tell Claude:"
echo "  • Which tests PASSED ✅"
echo "  • Which tests FAILED ❌"
echo "  • Any error messages you see"
echo ""
